version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    command: sleep infinity
    logging:
      driver: local
    volumes:
      - ".:/home/vscode/workspace:z"
