server:
  port: ${EUREKA_PORT}

spring:
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}

eureka:
  environment: prod

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    "[com.netflix.eureka]": info
    "[com.netflix.discovery]": info
