server:
  port: 8761

spring:
  main:
    banner-mode: off
  application:
    name: ms-eureka
  security:
    user:
      name: admin
      password: p@ssw0rd

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,logfile
    jmx:
      exposure:
        include: ${management.endpoints.web.exposure.include}

logging:
  level:
    "[com.netflix.eureka]": info
    "[com.netflix.discovery]": info
  file:
    name: ${LOG_PATH:./log}/${spring.application.name}.log
